# Generated by Django 5.1.7 on 2025-04-02 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_licence_number_driver_license_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={"verbose_name": "car", "verbose_name_plural": "cars"},
        ),
        migrations.AlterModelOptions(
            name="driver",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
    ]
